### PR TITLE
fix `...zip` or  `...mp4` bug

### PR DESCRIPTION
**Pull request by tangdou1**
https://github.com/HelloZeroNet/ZeroUp/issues/8

### CODE REVIEW

**Comment by HelloZeroNet** [comment]
Can you please also add this fix to the .coffee file?

**Comment by tangdou1** [comment]
@HelloZeroNet @shortcutme 
Oh, forgot it. Added now.

**Comment by purplesyringa** [comment]
@HelloZeroNet Please either merge this or close this.

**Comment by HelloZeroNet** [comment]
Support files that has ".." in the name should be fixed by https://github.com/HelloZeroNet/ZeroNet/commit/1ed40b3b8292191d8fafd8767f9ed0742b62d6ba, so it's not necessary anymore

**Pull request closed without merging**
